### ISSUE TITLE
Windows errors

### ISSUE THREAD

**Issue by wwwald** [ScitoVation/plethem#2]
I installed the latest Plethem on a Windows 10 computer - regular path via RStudio, devtools-GitHub install.

We received the following errors in file `rapidPBPK/ui.R':
* missing comma on line 1225, just before the `tabPanel` that's listed there
* missing closing bracket at the end of the file, to close the `shinyUI` function call on line 803.

I must admit that on another computer, this error did _not_ show following the exact same procedure. 

Are these bugs in Plethem itself, or is there some other possible cause for this?

**Comment by snpendse** [comment]
Did you install it right away on the other computer? Since I am still working on some features, I may have inadvertently broke something. Will look into it and update it here...

**Comment by snpendse** [comment]
The bug was in plethem itself... I have since fixed it and tested it to make sure it works...
