### ISSUE TITLE
Blank Grey Overlay on Windows with Firefox/Chrome

### ISSUE THREAD

**Issue by thehoglet** [ScitoVation/plethem#4]
I installed the latest R, Rtools, and RStudio before trying this. I'm using Windows 7.

After following the installation instructions, I tried ```setUserDb()```. This failed with something like "File not found". Using the function source, I tried this:

```
my_setUserDb <- function () 
{
  userDbPath <- rstudioapi::selectFile(caption = "Select User database", 
                                       filter = "*.sqlite", existing = F)
  query <- sprintf("Update Utils Set value = '%s' Where variable = 'UserDbPath';", 
                   userDbPath)
  mainDbUpdate(query)
  query <- "Select chemid from ChemicalSet;"
  result <- userDbSelect(query)
  print(sprintf("Selected User Database has %i chemicals", 
                length(result$chemid)))
}
```

where ```existing``` is now set to False and ```filter``` is a glob. The query fails with:

```Error in result_create(conn@ptr, statement) : no such table: ChemicalSet```

I started the app and tried to configure a model. Several times I was presented with a blank overlay where (presumably) a dialog should be presented. Pressing F5 to reload seemed not to lose my settings so far so I guess you are using session storage of some kind. This allowed me to press on, but only so far. Eventually all options lead to blank HTML overlay.

Is this a SQLite problem? An empty .sqlite file is created but never updated. When I exit, a .rdata file is created. loadProject() fails -- I guess for similar reasons that setUserDb() does. 

Some of the diagnostics produced included:

```
Warning in sprintf("SELECT param,value FROM Chemical Where chemid = %i",  :
  NAs introduced by coercion
Warning: Error in result_create: no such column: NA
  83: <Anonymous>
Warning: Error in result_create: near ";": syntax error
  84: <Anonymous>
Warning: Error in result_create: near ";": syntax error
  84: <Anonymous>
```

**Comment by snpendse** [comment]
I had to change the way setUserDb works. I could not find a way to select or create a new file if none exists from one function on a Mac. So the user database functions are now split into setUserDb() to select an existing one and createUserDb() to create a new one. I have updated the readme accordingly
