### ISSUE TITLE
Warning: Error in : shinyjs: extendShinyjs: `functions` argument must be provided.

### ISSUE THREAD

**Issue by ianedhlund** [ScitoVation/plethem#6]
> interactivePBPK(name="rapidPBPK")

Listening on http://127.0.0.1:3562
Warning: Error in : shinyjs: extendShinyjs: `functions` argument must be provided.
  82: stop
  81: errMsg
  80: shinyjs::extendShinyjs
Warning: Error in : shinyjs: extendShinyjs: `functions` argument must be provided.
  82: stop
  81: errMsg
  80: shinyjs::extendShinyjs

**Comment by bronsonk0619** [comment]
The shinyjs package had an update that required us to update the extendShinyjs() functions. These changes have been made and this error should no longer occur.
