### ISSUE TITLE
Project Loading Not Working - shiny issue

### ISSUE THREAD

**Issue by Chrizsly** [ScitoVation/plethem#7]
Dear all,

when loading a PBPK project using loadProject(), a new browser window opens with the following error message: 
![image](https://user-images.githubusercontent.com/57939062/94555618-296a2100-025c-11eb-9fee-a84bd4698ec7.png)

I am not quite sure what's going on. I followed the installation guideline and am using GC as well as IE.

Thanks,

**Comment by bronsonk0619** [comment]
The shinyjs package had an update that required us to update the extendShinyjs() functions. These changes have been made and this error should no longer occur.

**Comment by Chrizsly** [comment]
re-installing works just fine, thanks for the quick fix!
